server:
  port: 80
spring:
  devtools:
    livereload:
      port: 81
  application:
    name: gateway-security
  profiles:
    include: db
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: provider
#          uri: lb://cloud-user-provider
#          predicates:
#            - Path=/api/**
