spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/mmg_frame_cloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
#    password: fanrenjie1024
    password: 123456
  #    hikari:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/mmg_frame_cloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
#      username: root
#      # 加密后的密码
#      password: 1db220ba4f39865afc5a04301dee6527
  # Redis
  redis:
    host: localhost
    port: 6379
    timeout: 5000ms
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mmg.datasource.entity
  type-enums-package: com.mmg.datasource.enums
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  #打印SQL
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
logging:
  level:
    com.mmg.datasource.mapper: debug
