server:
  port: 8081
spring:
  profiles:
    include: db
  application:
    name: cloud-user-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: false
